/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeagenciadeviajes;

/**
 *
 * @author x360
 */
public class BuscarVueloResultados extends javax.swing.JFrame {

  /**
   * Creates new form BuscarVueloResultados
   */
  public BuscarVueloResultados() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    ResutadosBusquedaVuelo = new javax.swing.JTable();
    lblOrigen = new javax.swing.JLabel();
    txtfOrigen = new javax.swing.JTextField();
    lblDestino = new javax.swing.JLabel();
    txtfDestino = new javax.swing.JTextField();
    lblFechaDePartida = new javax.swing.JLabel();
    txtfFechaDePartida = new javax.swing.JTextField();
    lblFechaDeRegreso = new javax.swing.JLabel();
    txtfFechaDeRegreso = new javax.swing.JTextField();
    lblCantidadDeAdultos = new javax.swing.JLabel();
    txtfCantidadDeAdultos = new javax.swing.JTextField();
    lblCantidadDeMenores = new javax.swing.JLabel();
    txtfCantidadDeMenores = new javax.swing.JTextField();
    btnNuevaBusqueda = new javax.swing.JButton();
    btnRegresar = new javax.swing.JButton();
    txtfVuelos = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    ResutadosBusquedaVuelo.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Vuelo", "Fecha de partida", "Fecha de regreso", "Aereolinea"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }
    });
    jScrollPane1.setViewportView(ResutadosBusquedaVuelo);

    lblOrigen.setText("*Origen de vuelo");

    txtfOrigen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtfOrigenActionPerformed(evt);
      }
    });

    lblDestino.setText("*Destino de vuelo");

    lblFechaDePartida.setText("*Fecha de partida del vuelo");

    lblFechaDeRegreso.setText("Fecha de regreso del vuelo");

    lblCantidadDeAdultos.setText("*Cantidad de adultos en el vuelo");

    lblCantidadDeMenores.setText("*Cantidad de menores en el vuelo");

    btnNuevaBusqueda.setText("Nueva búsqueda");
    btnNuevaBusqueda.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnNuevaBusquedaActionPerformed(evt);
      }
    });

    btnRegresar.setText("Regresar");

    txtfVuelos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    txtfVuelos.setText(" Vuelos a [destino]");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(352, 352, 352)
            .addComponent(btnNuevaBusqueda)
            .addGap(149, 149, 149)
            .addComponent(btnRegresar))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(81, 81, 81)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jScrollPane1)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lblFechaDePartida)
                  .addComponent(lblCantidadDeAdultos)
                  .addComponent(lblOrigen))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtfCantidadDeAdultos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfFechaDePartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lblDestino)
                  .addComponent(lblFechaDeRegreso)
                  .addComponent(lblCantidadDeMenores))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(txtfCantidadDeMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                      .addComponent(txtfFechaDeRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(415, 415, 415)
            .addComponent(txtfVuelos)))
        .addContainerGap(59, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addComponent(txtfVuelos)
        .addGap(46, 46, 46)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(38, 38, 38)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblOrigen)
          .addComponent(txtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblDestino)
          .addComponent(txtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(21, 21, 21)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblFechaDePartida)
          .addComponent(txtfFechaDePartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblFechaDeRegreso)
          .addComponent(txtfFechaDeRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(25, 25, 25)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblCantidadDeAdultos)
          .addComponent(txtfCantidadDeAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCantidadDeMenores)
          .addComponent(txtfCantidadDeMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(46, 46, 46)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnNuevaBusqueda)
          .addComponent(btnRegresar))
        .addContainerGap(63, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtfOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfOrigenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtfOrigenActionPerformed

  private void btnNuevaBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaBusquedaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnNuevaBusquedaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BuscarVueloResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BuscarVueloResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BuscarVueloResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BuscarVueloResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BuscarVueloResultados().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable ResutadosBusquedaVuelo;
  private javax.swing.JButton btnNuevaBusqueda;
  private javax.swing.JButton btnRegresar;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblCantidadDeAdultos;
  private javax.swing.JLabel lblCantidadDeMenores;
  private javax.swing.JLabel lblDestino;
  private javax.swing.JLabel lblFechaDePartida;
  private javax.swing.JLabel lblFechaDeRegreso;
  private javax.swing.JLabel lblOrigen;
  private javax.swing.JTextField txtfCantidadDeAdultos;
  private javax.swing.JTextField txtfCantidadDeMenores;
  private javax.swing.JTextField txtfDestino;
  private javax.swing.JTextField txtfFechaDePartida;
  private javax.swing.JTextField txtfFechaDeRegreso;
  private javax.swing.JTextField txtfOrigen;
  private javax.swing.JLabel txtfVuelos;
  // End of variables declaration//GEN-END:variables
}
