/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemadeagenciadeviajes;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author x360
 */
public class BuscarVuelo extends javax.swing.JFrame {

  /**
   * Creates new form BuscarVuelo
   */
  public BuscarVuelo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblOrigen = new javax.swing.JLabel();
    lblDestino = new javax.swing.JLabel();
    lblFechaDePartida = new javax.swing.JLabel();
    lblFechaDeRegreso = new javax.swing.JLabel();
    lblCantidadDeAdultos = new javax.swing.JLabel();
    lblCantidadDeMenores = new javax.swing.JLabel();
    txtfOrigen = new javax.swing.JTextField();
    txtfDestino = new javax.swing.JTextField();
    txtfFechaDePartida = new javax.swing.JTextField();
    txtfFechaDeRegreso = new javax.swing.JTextField();
    txtfCantidadDeAdultos = new javax.swing.JTextField();
    txtfCantidadDeMenores = new javax.swing.JTextField();
    btnBuscar = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();
    lblImagen = new javax.swing.JLabel();
    txtfAdvertencia = new javax.swing.JLabel();
    txtfBuscarVuelo = new javax.swing.JLabel();
    txtfBuscarHotel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    lblOrigen.setText("*Origen de vuelo");

    lblDestino.setText("*Destino de vuelo");

    lblFechaDePartida.setText("*Fecha de partida del vuelo");

    lblFechaDeRegreso.setText("Fecha de regreso del vuelo");

    lblCantidadDeAdultos.setText("*Cantidad de adultos en el vuelo");

    lblCantidadDeMenores.setText("*Cantidad de menores en el vuelo");

    txtfOrigen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtfOrigenActionPerformed(evt);
      }
    });

    btnBuscar.setText("Buscar");
    btnBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarActionPerformed(evt);
      }
    });

    btnLimpiar.setText("Limpiar");

    lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemadeagenciadeviajes/images/oferta.PNG"))); // NOI18N

    txtfAdvertencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    txtfAdvertencia.setForeground(new java.awt.Color(255, 0, 0));
    txtfAdvertencia.setText("Los campos marcados con un \"*\" deben ser llenados obligatoriamente");

    txtfBuscarVuelo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    txtfBuscarVuelo.setText("Buscar vuelo");

    txtfBuscarHotel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txtfBuscarHotel.setText("Buscar Hotel");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(txtfBuscarVuelo)
        .addGap(410, 410, 410))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(72, 72, 72)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(txtfBuscarHotel)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(lblFechaDePartida)
                  .addComponent(lblFechaDeRegreso)
                  .addComponent(lblCantidadDeAdultos)
                  .addComponent(lblCantidadDeMenores)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrigen)
                    .addComponent(lblDestino)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtfCantidadDeAdultos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfCantidadDeMenores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfFechaDeRegreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfFechaDePartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtfOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(txtfAdvertencia, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(106, 106, 106)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar))
              .addComponent(lblImagen))))
        .addContainerGap(119, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(45, 45, 45)
        .addComponent(txtfBuscarVuelo)
        .addGap(23, 23, 23)
        .addComponent(txtfBuscarHotel)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblOrigen))
              .addGap(63, 63, 63)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblDestino))
              .addGap(56, 56, 56)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfFechaDePartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblFechaDePartida))
              .addGap(73, 73, 73)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfFechaDeRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblFechaDeRegreso))
              .addGap(71, 71, 71)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtfCantidadDeAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblCantidadDeAdultos))
              .addGap(72, 72, 72)
              .addComponent(txtfCantidadDeMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(lblCantidadDeMenores))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnBuscar)
          .addComponent(btnLimpiar)
          .addComponent(txtfAdvertencia))
        .addGap(35, 35, 35))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtfOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfOrigenActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtfOrigenActionPerformed

  private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnBuscarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BuscarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BuscarVuelo().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnBuscar;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblCantidadDeAdultos;
  private javax.swing.JLabel lblCantidadDeMenores;
  private javax.swing.JLabel lblDestino;
  private javax.swing.JLabel lblFechaDePartida;
  private javax.swing.JLabel lblFechaDeRegreso;
  private javax.swing.JLabel lblImagen;
  private javax.swing.JLabel lblOrigen;
  private javax.swing.JLabel txtfAdvertencia;
  private javax.swing.JLabel txtfBuscarHotel;
  private javax.swing.JLabel txtfBuscarVuelo;
  private javax.swing.JTextField txtfCantidadDeAdultos;
  private javax.swing.JTextField txtfCantidadDeMenores;
  private javax.swing.JTextField txtfDestino;
  private javax.swing.JTextField txtfFechaDePartida;
  private javax.swing.JTextField txtfFechaDeRegreso;
  private javax.swing.JTextField txtfOrigen;
  // End of variables declaration//GEN-END:variables
}
